#ifndef CONFIG_H
#define CONFIG_H

#define PI 3.14159265

#define COLOR Qt::black

#define SUCCES_STATUS 0

#define ERROR_STATUS 1
#define ERROR_STATUS_OPEN_FILE 2
#define ERROR_STATUS_FILE_DATA 3
#define ERROR_STATUS_MEMORY 4
#define ERROR_STATUS_POINTS 5
#define ERROR_STATUS_LINKS 6
#define ERROR_STATUS_FIELDS 7
#define ERROR_STATUS_VECTORS 8
#define ERROR_STATUS_LINKS_POINTS 9
#define ERROR_STATUS_TO_DO 10

#define NUMBER_OF_NUMS 2
#define NUMBER_OF_COORDINATES 3

#endif // CONFIG_H
