# task_1.EXE
task_1.exe : task_1.o 
	gcc -o app.exe task_1.o

task_1.o :
	gcc -std=gnu99 -Wall -Werror -ggdb -pedantic -c -o task_1.o t_1.c

# task_2.EXE
task_2.exe : task_2.o 
	gcc -o app.exe task_2.o

task_2.o :
	gcc -std=gnu99 -Wall -Werror -ggdb -pedantic -c -o task_2.o t_2.c

clear :
	rm *.o *exe