# task_1.EXE
task_1.exe : task_1.o 
	gcc -o app.exe task_1.o

task_1.o :
	gcc -c -o task_1.o p_1.c

# task_2.EXE
task_2.exe : task_2.o 
	gcc -o app.exe task_2.o

task_2.o :
	gcc -c -o task_2.o p_2.c

clear :
	rm *.o *exe